#!/bin/bash
#
#!/usr/bin/env bash

#git config credential.helper store
REPOSRC="https://github.com/maurya777/test-sub.git"
LOCALREPO="test-sub"
ORIGREPOLOC=$PWD
COMMIT_MSG=$1

printf "${ORIGREPOLOC}";

# printf "${GIT_DIR}\n"
# printf "${GIT_WORK_TREE}\n"
# exit 1

printf "cd /tmp\n";
cd /tmp

printf "rm -rf ${LOCALREPO}\n";
rm -rf ${LOCALREPO}
printf "git clone ${REPOSRC} ${LOCALREPO}\n";
git clone ${REPOSRC} ${LOCALREPO}

printf "cp -R ${ORIGREPOLOC}/${LOCALREPO}/* /tmp/${LOCALREPO}/\n";
cp -R ${ORIGREPOLOC}/${LOCALREPO}/* /tmp/${LOCALREPO}/

cd /tmp/${LOCALREPO}
printf "git add .\n";
git add .
printf "git commit -m ${COMMIT_MSG}\n";
git commit -m "$COMMIT_MSG"
printf "git push\n";
git push